[package]
name = "matched_parentheses_codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
symbols = { path = "symbols" }

[build-dependencies]
inator-automata = { path = "../.." }
symbols = { path = "symbols" }
